#!/bin/bash

#check to make sure that we're not already loading
#TODO: make override variable
if [[ -e /etc/mysql/my.cnf.loading_in_progress ]]; then
    echo "loading is already in progress.."
    exit 1
fi

#save state
sudo mv /etc/mysql/my.cnf /etc/mysql/my.cnf.loading_in_progress

#push the dbload configuration
sudo mv /etc/mysql/my.cnf.dbload  /etc/mysql/my.cnf

#restart mysql
sudo /etc/init.d/mysql restart


