#!/usr/bin/env python
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('input', nargs='?', default=sys.stdin)
args = parser.parse_args()
s = args.input
if isinstance(s, file):
   s = s.read()

_ ,tn, loc = s.strip().split(' ')
loc = loc.strip('()')
path, _, name = loc.rpartition('.')
print (path + ':' + name + '.' + tn)
sys.exit(0)